---

# roles/sinopia/tasks/main.yml

- name: Install sinopia
  npm:
    global: yes
    name: sinopia
    production: yes
    state: present

- name: Configure Sinopia
  template:
    src: templates/sinopia.conf.j2
    dest: /etc/sinopia.conf

- name: Run Sinopia
  command: sinopia --listen {{ port }} --config /etc/sinopia.conf

- name: Open the sinopia port on the firewall
  lineinfile:
    backup: yes
    dest: /etc/iptables.rules
    insertbefore: "^COMMIT"
    line: "-A INPUT -p tcp --dport {{ port }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"
    state: present
  notify: restart iptables
