---

# these steps are followed from : http://www.redmine.org/projects/redmine/wiki/RedmineInstall

- name:            Install OS prerequisites
  become:          true
  apt:
      name:        "{{ item }}"
  with_items:
    - apache2
    - libapache2-mod-passenger
    - imagemagick


- name:            Set Rails ENV to production
  become:          yes
  lineinfile:
    path:          /etc/profile
    line:          export RAILS_ENV=production

- name:            Set REDMINE_LANG to english
  become:          yes
  lineinfile:
    path:          /etc/profile
    line:          export REDMINE_LANG=en

- name:            Step 1 - Fetch the redmine package
  get_url:
    backup:        yes
    checksum:      "{{ redmine_release_checksum }}"
    url:           http://www.redmine.org/releases/redmine-{{ redmine_release }}.zip
    dest:          "."

- name:            Unpack the redmine package
  become:          true
  unarchive:
    dest:          "{{ redmine_location }}"
    remote_src:    yes
    src:           "./redmine-{{ redmine_release }}.zip"
    group:         ubuntu
    owner:         ubuntu


- name:            Step 2a - Create role in database
  become:          true
  become_user:     postgres
  postgresql_user:
    name:          "{{ redmine_database_username }}"
    password:      "{{ redmine_database_password }}"
    state:         present

- name:            Step 2b - Create the database
  become:          true
  become_user:     postgres
  postgresql_db:
    name:          "{{ redmine_database_name }}"
    encoding:      UTF-8
    owner:         "{{ redmine_database_username }}"
    state:         present

- name:            Step 3 - Database connection configuration
  become:          true
  template:
    src:           templates/database_yml
    backup:        yes
    dest:          "{{ redmine_location }}/redmine-{{ redmine_release }}/config/database.yml"

- name:            Step 4a - Dependencies installations
  gem:
    executable:    /home/ubuntu/.rbenv/shims/gem
    name:          "{{ item }}"
    state:         present
  with_items:
    - pg

- name:            Step 4b - Dependencies installations
  bundler:
    executable:    /home/ubuntu/.gem/ruby/2.4.0/bin/bundle
    extra_args:    --without development test
    chdir:         "{{ redmine_location }}/redmine-{{ redmine_release }}"
    state:         present

- name:            Step 5 - Session store secret generation
  shell:           $HOME/.gem/ruby/2.4.0/bin/bundle exec $HOME/.rbenv/shims/rake generate_secret_token
  args:
    chdir:         "{{ redmine_location }}/redmine-{{ redmine_release }}"

- name:            Step 6 - Database schema objects creation
  shell:           RAILS_ENV=production $HOME/.gem/ruby/2.4.0/bin/bundle exec $HOME/.rbenv/shims/rake db:migrate
  args:
    chdir:         "{{ redmine_location }}/redmine-{{ redmine_release }}"

- name: Step 7 - Database default data set
  shell:           RAILS_ENV=production bundle exec rake redmine:load_default_data
  args:
    chdir:         "{{ redmine_location }}/redmine-{{ redmine_release }}"
