---

# roles/virtual_private_cloud/tasks/main.yml

- name:                Create VPC and subnets
  ec2_vpc_net:
    state:             present
    name:              "{{ vpc_name }}"
    cidr_block:        "{{ vpc_cidr_block }}"
    region:            "{{ region }}"
    tags:
      Name:            "{{ vpc_name }}"
  register:            vpc

- debug:
    msg: "VPC: {{vpc}}"

- name:                setup subnet(s)
  ec2_vpc_subnet:
    state:             present
    cidr:              "{{ vpc_cidr_block }}"
    region:            "{{ region }}"
    az:                "{{ zone }}"
    vpc_id:            "{{ vpc.vpc.id }}"
    tags:
      Name:            "{{ subnet_name }}"
  register:            subnets

- name:                setup routing table
  ec2_vpc_route_table:
    state:             present
    vpc_id:            "{{ vpc.vpc.id }}"
    region:            "{{ region }}"    
    tags:
      Name:            "{{ routing_name }}"
  register:            routing_tables

- name:                get igw
  ec2_vpc_igw:
    state:             present
    vpc_id:            "{{ vpc.vpc.id }}"
    region:            "{{ region }}"
  register:            igw

- name:                Set the igw name
  ec2_tag:
    resource:          "{{item}}"
    state:             present
    region:            "{{ region }}"
    tags:
      Name:            "{{ gateway_name }}"
  with_items:
    - "{{ igw.gateway_id }}"
