---

# roles/jenkins/tasks/main.yml

- name: Create Jenkins directory in /data
  file:
    path: /data/jenkins
    state: directory
    mode: 0777

- name: Install key
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - jenkins
    - build-essential

- name: Install global node packages
  npm:
    global: yes
    name: "{{item}}"
    production: yes
    state: latest
  with_items:
    - db-migrate
    - db-migrate-pg
    - babel-cli

- name: Open the Jenkins ports on the firewall
  lineinfile:
    backup: yes
    dest: /etc/iptables.rules
    insertbefore: "^COMMIT"
    line: "-A INPUT -p tcp --dport {{item}} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"
    state: present
  with_items:
    - 8080
    - 5000
  notify: restart iptables
