---

# /roles/common/tasks/main.yml


- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Initial configure of iptables
  become: true
  template:
    src: templates/iptables.j2
    dest: /etc/iptables.rules

- name: Copy iptables support files to servrer
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'files/iptablesload', dest: '/etc/network/if-pre-up.d', owner: 'root', group: 'root', mode: '744'}
    - { src: 'files/iptablessave', dest: '/etc/network/if-post-down.d', owner: 'root', group: 'root', mode: '744'}
  notify: restart iptables