---

#roles/artifactory/tasks/all

- name: Add 3rd party repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://jfrog.bintray.com/artifactory-debs xenial main

- name: Add key
  apt_key:
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=jfrog"
    state: present

- name: Update Cache
  apt:
    update_cache: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items:
    - jfrog-artifactory-oss

- name: Copy default config
  copy:
    src: files/default
    dest: /etc/opt/jfrog/artifactory

- name: Copy server.xml
  template:
    src: templates/server.xml.j2
    dest: /opt/jfrog/artifactory/tomcat/conf/server.xml

- name: Setup as a service
  service:
    name: artifactory
    enabled: yes
    state: restarted

- name: Open the artifactory port on the firewall
  lineinfile:
    backup: yes
    dest: /etc/iptables.rules
    insertbefore: "^COMMIT"
    line: "-A INPUT -p tcp --dport {{connector_port}} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT"
    state: present
  notify: restart iptables

