---

#roles/artifactory/tasks/all

- name: Add 3rd party repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://jfrog.bintray.com/artifactory-debs xenial main

- name: Add key
  apt_key:
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=jfrog"
    state: present

- name: Update Cache
  apt:
    update_cache: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - jfrog-artifactory-oss

- name: Setup as a service
  service:
    name: artifactory
    state: started

