---

# roles/servers/tasks/docker.yml

- name: Create Docker Server
  ec2:
    key_name: "{{ application }}"
    count_tag:
      - server_type: docker
    exact_count: "{{ minimum_number_of_docker_servers }}"
    zone: "{{ zone }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    wait: yes
    group_id: "{{ security_group }}"
    instance_tags:
      Name: "{{application}}-docker"
      application: "{{application}}"
      server_type: docker
      os: "xenial"
  register: created

- name: Create ebs volume
  ec2_vol:
    instance: "{{ item.id }}"
    region: "{{ region }}"
    volume_size: 10
    state: present
  with_items:
    - "{{ created.instances }}"
