---

# roles/servers/tasks/main.yml

- include: java_repo.yml

- name: Add all the new instances to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items:
    - "{{ created_artifactory.instances }}"

- name: Refresh EC2 cache
  command: inventory/ec2.py --refresh-cache

- name: Refresh in-memory EC2 cache
  meta: refresh_inventory

#- name: Wait for SSH to come up on all the servers
#  wait_for:
#    host: "{{ item.public_dns_name }}"
#    port: 22
#    delay: 60
#    timeout: 320
#    state: started
#  with_items:
#    - "{{ created_artifactory.instances }}"