---

# roles/servers/tasks/main.yml

- include: java_repo.yml

- include: npm_repo.yml

- name: Refresh EC2 cache
  command: inventory/ec2.py --refresh-cache

- name: Refresh in-memory EC2 cache
  meta: refresh_inventory
