---

# roles/servers/tasks/npm_repo.yml

- name: Create NPM Repository Server
  ec2:
    key_name: "{{ application }}"
    count_tag:
      - server_type: npmrepo
    exact_count: "{{ minimum_number_of_npm_repo_servers }}"
    zone: "{{ zone }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    wait: yes
    group_id: "{{ security_group }}"
    instance_tags:
      Name: "{{application}}-npm_repo"
      application: "{{ application }}"
      server_type: npmrepo
      os: "xenial"
  register: created

- name: Create ebs volume
  ec2_vol:
    instance: "{{ item.id }}"
    region: "{{ region }}"
    volume_size: 10
    state: present
  with_items:
    - "{{ created.instances }}"
